services:
  db:
    networks:
      - spring-postgres
    image: postgres:latest
    container_name: imgproc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zv2afkk74Zd3czjmdzU4WSafi
      POSTGRES_DB: imageprocessing
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - maven-repo:/root/.m2
  app:
    build: .
    container_name: imgproc-service-app
    depends_on:
       db:
          condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"

    networks:
      - spring-postgres
volumes:
  db-data:
  maven-repo:
networks:
  spring-postgres: